prd:
  master:
    repository:
      isolationlevelforcreate: ISOLATION_DEFAULT #ISOLATION_DEFAULT #ISOLATION_READ_COMMITTED
    datasource:
      poolName: hikari-cp
      poolSize: 1
      maximumPoolSize: 1
      jdbcUrl: jdbc:log4jdbc:oracle:thin:@localhost:1521:accsys
      username: 
      password: 
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      autoCommit: true
      connectionTimeout: 30000
      validationTimeout: 250
      maxLifetime: 1750000
      mapUnderscoreToCamelCase: true
#  source:
#    repository:
#      isolationlevelforcreate: ISOLATION_DEFAULT
#    datasource:
#      poolName: hikari-cp
#      poolSize: 1
#      maximumPoolSize: 1
#      jdbcUrl: ${sourceJdbcUrl}
#      username: ${sourceUsername}
#      password: ${sourcePassword}
#      driverClassName: ${sourceDriverClassName}
#      autoCommit: true
#      connectionTimeout: 30000
#      validationTimeout: 250
#      maxLifetime: 1750000
#      mapUnderscoreToCamelCase: true
#  target:
#    repository:
#      isolationlevelforcreate: ISOLATION_DEFAULT
#    datasource:
#      poolName: hikari-cp
#      poolSize: 1
#      maximumPoolSize: 1
#      jdbcUrl: jdbc:log4jdbc:oracle:thin:@localhost:1623:target #${targetJdbcUrl}
#      username:  #${targetUsername}
#      password:  #${targetPassword}
#      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #${targetDriverClassName}
#      autoCommit: true
#      connectionTimeout: 30000
#      validationTimeout: 250
#      maxLifetime: 1750000
#      mapUnderscoreToCamelCase: true
