prd:
  master:
    repository:
      isolationlevelforcreate: ISOLATION_DEFAULT #ISOLATION_DEFAULT #ISOLATION_READ_COMMITTED
    datasource:
      poolName: hikari-cp
      poolSize: 1
      maximumPoolSize: 1
      jdbcUrl: jdbc:log4jdbc:oracle:thin:@localhost:1521:accsys
      username: MsYkAmPzhVYx9fMOinAF66lzSJ48Yp6WRtOEW+wbprrr8FiWmIfLpzXayT59m2RQyEH06w==
      password: CIcHFdq0ON9QSdVU8rCgO0NOEE9upfwpJvIb0PdfMIVAUX40yEiybWtgfcOVZOA6S5IogQ==
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      autoCommit: true
      connectionTimeout: 30000
      validationTimeout: 250
      maxLifetime: 1750000
      mapUnderscoreToCamelCase: true
#  source:
#    repository:
#      isolationlevelforcreate: ISOLATION_DEFAULT
#    datasource:
#      poolName: hikari-cp
#      poolSize: 1
#      maximumPoolSize: 1
#      jdbcUrl: ${sourceJdbcUrl}
#      username: ${sourceUsername}
#      password: ${sourcePassword}
#      driverClassName: ${sourceDriverClassName}
#      autoCommit: true
#      connectionTimeout: 30000
#      validationTimeout: 250
#      maxLifetime: 1750000
#      mapUnderscoreToCamelCase: true
#  target:
#    repository:
#      isolationlevelforcreate: ISOLATION_DEFAULT
#    datasource:
#      poolName: hikari-cp
#      poolSize: 1
#      maximumPoolSize: 1
#      jdbcUrl: jdbc:log4jdbc:oracle:thin:@localhost:1623:target #${targetJdbcUrl}
#      username: QNa84kbdlwDjfc7zC4dlxDsvLUZYLNgn8OzoBRyYlQbnpnlBRFqkO+2ErsLVwbZPjddkbg== #${targetUsername}
#      password: aZbK3FrEse1QhMCWmM4zAzQeO4ZS2KGoNsmMo/gFRzaZFXjmGrIfaKbDn7UrPj31w2RwQg== #${targetPassword}
#      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #${targetDriverClassName}
#      autoCommit: true
#      connectionTimeout: 30000
#      validationTimeout: 250
#      maxLifetime: 1750000
#      mapUnderscoreToCamelCase: true